### ISSUE TITLE
Unable to install MQTT Jmeter plugin 

### ISSUE THREAD

**Issue by anandsrn9** [hemikak/mqtt-jmeter#2]
Hi hemikak,

I tried the steps provided in URL :https://github.com/hemikak/mqtt-jmeter to install MQTT Plugin, downloaded MQTT Plugin : mqtt-jmeter-master zip from this site and tried running mvn clean install command from windows cmd prompt as per instructions provided, but mvn was not recognized and was not able to do that. Tried running cmd : ./installer.sh ~/Documents/wso2/mb/clients/apache-jmeter-2.13/
but that too didnt run stating '.' is not recognized as an internal and external command.

I am using Windows 7 OS, can you please update how to install MQTT plugin in Jmeter

Thanks,
Anand

**Comment by hemikak** [comment]
Hi @anandsrn9 ,

I have not tested this on windows platform. Sorry for the inconvenience. 

I will get back to you once I test this on a windows OS.

Regards,
Hemika

**Comment by hemikak** [comment]
Hi @anandsrn9 ,

I have added the batch script file to the project for windows platform : https://github.com/hemikak/mqtt-jmeter/blob/master/src/main/resources/installer.bat

Regards,
Hemika
