### ISSUE TITLE
CSV Data Set Config

### ISSUE THREAD

**Issue by IBloemen** [hemikak/mqtt-jmeter#5]
Hello Hemika

I want to use mqtt-jmeter to set up load tests for our MQTT servers. Therefore I would like to change the MQTT UI parameters per thread with  jmeter's "CSV Data Set Config" config element.
Although this works fine with MQTT Publisher Sampler,
it seems that CSV Data Set Config does not work with MQTT Subscriber Sampler, ie ${VAR} in UI are not recognised and used as plain strings, eg if I use ${TOPIC} in UI, then the clients subscribe to "${TOPIC}" iso a value of the corresponding column in cvs file of CSV Data Set Config. Also vars defined in Beanshell preprocessor are not recognised in Subscriber plugin.
Note that "User Defined Vars" in Test Plan config are supported, but this does not fit my purposes.
Thank you for your support.
Iris

**Comment by IBloemen** [comment]
Hello

It seems that the Jmeter vars defined in the MQTT Subscriber thread are not known in MQTT Subscriber Sampler. If I use ${__BeanShell(props.get("DEVICE_M"))} in the Sampler UI field, where the value of DEVICE_M is set with props.set n a BeanShell PreProcessor attached to MQTT Subscriber Sampler, then it works.
If I use vars.set/vars.get then it want, ie a null value is set in the UI field.

Best Regards,

Iris

**Comment by hemikak** [comment]
Hi @IBloemen ,

I will look into this issue when I get some time. Thanks for sharing the information and logging the issue.

I have not tested the vars within in the subscriber sample before. So I will look into it.

Regards,
Hemika

**Comment by IBloemen** [comment]
Hello Hemika

Thanks for the quick response.
I’m using following workaround now (which might be suboptimal fro load testing):
I read in a cvs fie with CVS Data Set Config, and copy the vars into props values with BeanShell Preprocessor. In the sampler UI field I use a BeanShell script to read in the props values.

Best Regards,

Iris

**Comment by hemikak** [comment]
Hi Iris
Can you provide me with the sample(jmx file) to run and see. It would be easy to debug.

Regards,
Hemika

**Comment by IBloemen** [comment]
Hello Hemika

Please find test script attached.
Test plan contains three thread groups:

Thread Group Mobile (work-around)
MQTT subscriber
copies CSV values to Jmeter’s global props variables
is disabled
Thread Group Mobile (not working)
MQTT subscriber
Thread Group STB 
MQTT Publisher
works
Best Regards,

Iris

**Comment by IBloemen** [comment]
- CSV files

**Comment by varunletsee** [comment]
Hi IBloemen,

I can't see the attached file. MQTT_test.jmx
Can you please upload it to githup and provide me the path.

Thanks
Varun Sharna

**Comment by hemikak** [comment]
Hi @IBloemen ,

Can you change the extension of the jmx file to txt and then drag and drop the file to the comments section ? 

Regards,
Hemika

**Comment by hemikak** [comment]
Please reopen if needed.

**Comment by martima** [comment]
does the MQTT plugin support input from CSV?

**Comment by NethraNaina** [comment]
Hi,

I am trying to read data from CSV and send it to Mqtt Publisher. But it is not reading data from csv or else  it is not replacing the csv variables into data.
Can anyone help?

I have data in CSV or JSON file.
