### ISSUE TITLE
Change in functionality request

### ISSUE THREAD

**Issue by edwardgroot** [hemikak/mqtt-jmeter#7]
Hi all,

First of all thanks a lot for putting all the effort into creating a plugin for mqtt in Jmeter. I have a problem with testing our new application with Jmeter. With soapui I have no issues, and we don't have the money for Loadui so I am looking for alternatives. 

The problem lies in the fact that we attach files in the xdr format which are being converted by this plugin. Is it possible to alter the plugin so that it also supports files in "raw" format for example? 

Thanks a lot.

Ed

**Comment by hemikak** [comment]
I will look into this in the next couple of days.

**Comment by hemikak** [comment]
Fixed : https://github.com/hemikak/mqtt-jmeter/commit/4d1dc492bcc13bf8f18ba468280dc714a6cc58c0
