### ISSUE TITLE
Jar signature mismatch resulting in jmeter stopping

### ISSUE THREAD

**Issue by amitmangalvedkar** [hemikak/mqtt-jmeter#8]
Hi,  
First and foremost, thanks for working on a plugin for MQTT. However, has this been tested with the latest MQTT Paho libraries for java, as on applying the plugin and running the jmeter, it consistently gives me this error 
`An error occurred: class "org.eclipse.paho.client.mqttv3.BufferedMessage"'s signer information does not match signer information of other classes in the same package`  

I have used Apache JMeter Version 3.1 on macOS Sierra 10.12.1 and the default JRE which comes with the JDK 1.8.0_92  

Thanks and Regards

**Comment by hemikak** [comment]
I will look into this in the next couple of days.

**Comment by amitmangalvedkar** [comment]
Actually, it was a mistake at my end - I had not added the messages.properties file in the jar. After adding the properties, this error goes away. So I am closing this issue. Thanks for considering to look into the issue.  

Thanks and Regards
